import { request } from './request'

// ============ 字典类型定义 ============
export type DictSourceType = 'manual' | 'view_ref' | 'auto'

// 字典映射项
export interface DictMapping {
  value: string
  label: string
  synonyms?: string[]
}

// 字典
export interface Dictionary {
  id: string
  name: string
  display_name?: string
  source_type: DictSourceType
  mappings?: DictMapping[]
  ref_view_id?: string
  ref_value_column?: string
  ref_label_column?: string
  auto_source_dataset_id?: string
  auto_source_column?: string
  auto_filters?: Array<{ column: string; operator: string; value: string }>
  auto_last_sync?: string
  description?: string
  created_at: string
  updated_at: string
}

// 字典值列表响应
export interface DictionaryValuesResponse {
  source_type: DictSourceType
  values: DictMapping[]
  last_sync?: string
}

// 自动生成请求
export interface AutoGenerateRequest {
  datasource_id: string
  dataset_id: string
  column_name: string
  dictionary_name: string
  filters?: Array<{ column: string; operator: string; value: string }>
  limit?: number
}

// 值解析请求
export interface ResolveValueRequest {
  label: string
}

// 批量解析请求
export interface BatchResolveRequest {
  labels: string[]
}

// ============ 字典管理 API ============

// 获取字典列表
export function getDictionaries(params?: { source_type?: string }): Promise<Dictionary[]> {
  return request.get('/dictionaries', { params })
}

// 获取单个字典详情
export function getDictionary(id: string): Promise<Dictionary> {
  return request.get(`/dictionaries/${id}`)
}

// 创建字典
export function createDictionary(data: Partial<Dictionary>): Promise<Dictionary> {
  return request.post('/dictionaries', data)
}

// 更新字典
export function updateDictionary(id: string, data: Partial<Dictionary>): Promise<Dictionary> {
  return request.put(`/dictionaries/${id}`, data)
}

// 删除字典
export function deleteDictionary(id: string): Promise<void> {
  return request.delete(`/dictionaries/${id}`)
}

// 获取字典值列表
export function getDictionaryValues(id: string): Promise<DictionaryValuesResponse> {
  return request.get(`/dictionaries/${id}/values`)
}

// 自动生成字典
export function autoGenerateDictionary(data: AutoGenerateRequest): Promise<Dictionary> {
  return request.post('/dictionaries/auto-generate', data)
}

// 同步字典
export function syncDictionary(id: string): Promise<Dictionary> {
  return request.post(`/dictionaries/${id}/sync`)
}

// 添加字典映射项
export function addMapping(id: string, mapping: DictMapping): Promise<Dictionary> {
  return request.post(`/dictionaries/${id}/mappings`, mapping)
}

// 删除字典映射项
export function deleteMapping(id: string, value: string): Promise<Dictionary> {
  return request.delete(`/dictionaries/${id}/mappings/${encodeURIComponent(value)}`)
}

// 解析单个值
export function resolveValue(id: string, data: ResolveValueRequest): Promise<{
  dict_id: string
  input: string
  resolved_value: string
  found: boolean
}> {
  return request.post(`/dictionaries/${id}/resolve-value`, data)
}

// 批量解析值
export function batchResolveValues(id: string, data: BatchResolveRequest): Promise<{
  dict_id: string
  results: Array<{
    input: string
    resolved_value: string
    found: boolean
  }>
}> {
  return request.post(`/dictionaries/${id}/batch-resolve`, data)
}

// 获取字典标签列表（用于 NL 提示）
export function getDictionaryLabels(id: string): Promise<{
  dict_id: string
  dict_name: string
  labels: string[]
}> {
  return request.get(`/dictionaries/${id}/labels`)
}

// 根据名称获取字典
export function getDictionaryByName(name: string): Promise<Dictionary> {
  return request.get(`/dictionaries/by-name/${name}`)
}

// 根据名称解析值
export function resolveByDictName(name: string, data: ResolveValueRequest): Promise<{
  dict_name: string
  input: string
  resolved_value: string
  found: boolean
}> {
  return request.post(`/dictionaries/by-name/${name}/resolve`, data)
}
