"""add_conversation_fields_to_query_history

Revision ID: feea14b28cbe
Revises: 6c116957672c
Create Date: 2026-02-05 15:16:15.477364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision = 'feea14b28cbe'
down_revision = '6c116957672c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False, comment='SQL语句'),
    sa.Column('depth', sa.String(length=20), nullable=True, comment='分析深度: table/column/operator'),
    sa.Column('result', sa.JSON(), nullable=True, comment='分析结果'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_analyses_id'), 'sql_analyses', ['id'], unique=False)
    op.create_table('data_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('left_dataset_id', sa.String(length=36), nullable=False),
    sa.Column('right_dataset_id', sa.String(length=36), nullable=False),
    sa.Column('join_type', sa.String(length=20), nullable=False),
    sa.Column('join_conditions', sa.JSON(), nullable=False),
    sa.Column('relationship_type', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['left_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['right_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sql_analysis')
    op.drop_table('relations')
    op.add_column('audit_logs', sa.Column('time', sa.String(length=50), nullable=True, comment='操作时间'))
    op.add_column('audit_logs', sa.Column('user', sa.String(length=100), nullable=True, comment='操作用户'))
    op.add_column('audit_logs', sa.Column('target', sa.String(length=200), nullable=True, comment='操作对象'))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('audit_logs', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               nullable=True,
               comment='操作类型')
    op.alter_column('audit_logs', 'details',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               comment='操作详情',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'resource_type')
    op.add_column('consolidation_rules', sa.Column('type', sa.String(length=20), nullable=False, comment='规则类型: merge/clean/transform'))
    op.add_column('consolidation_rules', sa.Column('source_tables', sa.JSON(), nullable=True, comment='源表列表'))
    op.add_column('consolidation_rules', sa.Column('target_table', sa.String(length=200), nullable=True, comment='目标表'))
    op.add_column('consolidation_rules', sa.Column('strategy', sa.String(length=50), nullable=True, comment='合并策略'))
    op.add_column('consolidation_rules', sa.Column('condition', sa.Text(), nullable=True, comment='条件/逻辑'))
    op.add_column('consolidation_rules', sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'))
    op.add_column('consolidation_rules', sa.Column('exec_count', sa.Integer(), nullable=True, comment='执行次数'))
    op.alter_column('consolidation_rules', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('consolidation_rules', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='规则名称',
               existing_nullable=False)
    op.alter_column('consolidation_rules', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_consolidation_rules_id'), 'consolidation_rules', ['id'], unique=False)
    op.drop_column('consolidation_rules', 'is_active')
    op.drop_column('consolidation_rules', 'apply_to')
    op.drop_column('consolidation_rules', 'rule_config')
    op.add_column('data_accelerations', sa.Column('type', sa.String(length=50), nullable=False, comment='加速类型: materialized_view/cube/cache'))
    op.add_column('data_accelerations', sa.Column('source_table', sa.String(length=200), nullable=True, comment='源表'))
    op.add_column('data_accelerations', sa.Column('query', sa.Text(), nullable=True, comment='加速SQL'))
    op.add_column('data_accelerations', sa.Column('refresh_policy', sa.String(length=50), nullable=True, comment='刷新策略'))
    op.add_column('data_accelerations', sa.Column('schedule', sa.String(length=100), nullable=True, comment='刷新周期'))
    op.add_column('data_accelerations', sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'))
    op.add_column('data_accelerations', sa.Column('speedup', sa.Integer(), nullable=True, comment='加速比'))
    op.add_column('data_accelerations', sa.Column('original_latency', sa.Integer(), nullable=True, comment='原始延迟(ms)'))
    op.add_column('data_accelerations', sa.Column('accelerated_latency', sa.Integer(), nullable=True, comment='加速后延迟(ms)'))
    op.add_column('data_accelerations', sa.Column('next_run', sa.String(length=50), nullable=True, comment='下次执行'))
    op.add_column('data_accelerations', sa.Column('storage', sa.String(length=50), nullable=True, comment='存储占用'))
    op.add_column('data_accelerations', sa.Column('last_refresh', sa.String(length=50), nullable=True, comment='上次刷新'))
    op.add_column('data_accelerations', sa.Column('cache_size', sa.String(length=50), nullable=True, comment='缓存大小'))
    op.alter_column('data_accelerations', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('data_accelerations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='任务名称',
               existing_nullable=False)
    op.alter_column('data_accelerations', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_data_accelerations_id'), 'data_accelerations', ['id'], unique=False)
    op.drop_constraint('data_accelerations_ibfk_1', 'data_accelerations', type_='foreignkey')
    op.drop_column('data_accelerations', 'acceleration_config')
    op.drop_column('data_accelerations', 'last_refresh_at')
    op.drop_column('data_accelerations', 'refresh_schedule')
    op.drop_column('data_accelerations', 'status')
    op.drop_column('data_accelerations', 'source_dataset_id')
    op.add_column('integration_tasks', sa.Column('source_type', sa.String(length=50), nullable=False, comment='源数据类型'))
    op.add_column('integration_tasks', sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标数据类型'))
    op.add_column('integration_tasks', sa.Column('schedule', sa.String(length=100), nullable=True, comment='调度策略'))
    op.add_column('integration_tasks', sa.Column('schedule_type', sa.String(length=20), nullable=True, comment='调度类型: cron/interval/manual'))
    op.add_column('integration_tasks', sa.Column('cron_expr', sa.String(length=100), nullable=True, comment='Cron表达式'))
    op.add_column('integration_tasks', sa.Column('interval_minutes', sa.Integer(), nullable=True, comment='执行间隔(分钟)'))
    op.add_column('integration_tasks', sa.Column('last_run_time', sa.String(length=50), nullable=True, comment='上次执行时间'))
    op.add_column('integration_tasks', sa.Column('last_run_duration', sa.String(length=50), nullable=True, comment='执行耗时'))
    op.alter_column('integration_tasks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('integration_tasks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='任务名称',
               existing_nullable=False)
    op.alter_column('integration_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态: running/paused/failed/success',
               existing_nullable=True)
    op.alter_column('integration_tasks', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_integration_tasks_id'), 'integration_tasks', ['id'], unique=False)
    op.drop_column('integration_tasks', 'target_config')
    op.drop_column('integration_tasks', 'source_config')
    op.drop_column('integration_tasks', 'schedule_config')
    op.drop_column('integration_tasks', 'last_run_at')
    op.add_column('lineage_connections', sa.Column('from_node', sa.String(length=100), nullable=False, comment='源节点ID'))
    op.add_column('lineage_connections', sa.Column('to_node', sa.String(length=100), nullable=False, comment='目标节点ID'))
    op.add_column('lineage_connections', sa.Column('color', sa.String(length=20), nullable=True, comment='连接线颜色'))
    op.alter_column('lineage_connections', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lineage_connections', 'connection_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               comment='连接类型')
    op.create_index(op.f('ix_lineage_connections_id'), 'lineage_connections', ['id'], unique=False)
    op.drop_constraint('lineage_connections_ibfk_2', 'lineage_connections', type_='foreignkey')
    op.drop_constraint('lineage_connections_ibfk_1', 'lineage_connections', type_='foreignkey')
    op.drop_column('lineage_connections', 'target_node_id')
    op.drop_column('lineage_connections', 'source_node_id')
    op.drop_column('lineage_connections', 'updated_at')
    op.drop_column('lineage_connections', 'properties')
    op.add_column('lineage_nodes', sa.Column('node_id', sa.String(length=100), nullable=False, comment='节点ID'))
    op.add_column('lineage_nodes', sa.Column('type', sa.String(length=50), nullable=True, comment='算子类型'))
    op.add_column('lineage_nodes', sa.Column('detail', sa.Text(), nullable=True, comment='详情'))
    op.add_column('lineage_nodes', sa.Column('fields', sa.JSON(), nullable=True, comment='字段列表'))
    op.add_column('lineage_nodes', sa.Column('execution_time', sa.String(length=50), nullable=True, comment='执行时间'))
    op.add_column('lineage_nodes', sa.Column('row_count', sa.String(length=50), nullable=True, comment='行数'))
    op.add_column('lineage_nodes', sa.Column('upstream', sa.JSON(), nullable=True, comment='上游节点'))
    op.add_column('lineage_nodes', sa.Column('downstream', sa.JSON(), nullable=True, comment='下游节点'))
    op.alter_column('lineage_nodes', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lineage_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='节点名称',
               existing_nullable=False)
    op.alter_column('lineage_nodes', 'node_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=20),
               comment='节点类型: source/operator/target',
               existing_nullable=False)
    op.create_index(op.f('ix_lineage_nodes_id'), 'lineage_nodes', ['id'], unique=False)
    op.create_unique_constraint(None, 'lineage_nodes', ['node_id'])
    op.drop_column('lineage_nodes', 'properties')
    op.drop_column('lineage_nodes', 'data_source')
    op.add_column('metric_accelerations', sa.Column('metric_name', sa.String(length=200), nullable=False, comment='指标名称'))
    op.add_column('metric_accelerations', sa.Column('metric_code', sa.String(length=100), nullable=False, comment='指标编码'))
    op.add_column('metric_accelerations', sa.Column('dimensions', sa.JSON(), nullable=True, comment='预聚合维度'))
    op.add_column('metric_accelerations', sa.Column('granularity', sa.String(length=20), nullable=True, comment='时间粒度'))
    op.add_column('metric_accelerations', sa.Column('refresh_policy', sa.String(length=50), nullable=True, comment='刷新策略'))
    op.add_column('metric_accelerations', sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'))
    op.add_column('metric_accelerations', sa.Column('hit_rate', sa.Integer(), nullable=True, comment='命中率(%)'))
    op.add_column('metric_accelerations', sa.Column('original_latency', sa.Integer(), nullable=True, comment='原始延迟(ms)'))
    op.add_column('metric_accelerations', sa.Column('accelerated_latency', sa.Integer(), nullable=True, comment='加速后延迟(ms)'))
    op.add_column('metric_accelerations', sa.Column('last_refresh', sa.String(length=50), nullable=True, comment='上次刷新'))
    op.add_column('metric_accelerations', sa.Column('cache_size', sa.String(length=50), nullable=True, comment='缓存大小'))
    op.alter_column('metric_accelerations', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_metric_accelerations_id'), 'metric_accelerations', ['id'], unique=False)
    op.drop_column('metric_accelerations', 'metric_id')
    op.drop_column('metric_accelerations', 'acceleration_config')
    op.drop_column('metric_accelerations', 'description')
    op.drop_column('metric_accelerations', 'refresh_interval')
    op.drop_column('metric_accelerations', 'name')
    op.drop_column('metric_accelerations', 'last_calculated_at')
    op.drop_column('metric_accelerations', 'status')
    op.add_column('metric_applications', sa.Column('type', sa.String(length=20), nullable=False, comment='应用类型: dashboard/report/api'))
    op.add_column('metric_applications', sa.Column('metrics', sa.JSON(), nullable=True, comment='包含的指标列表'))
    op.add_column('metric_applications', sa.Column('owner', sa.String(length=100), nullable=True, comment='负责人'))
    op.add_column('metric_applications', sa.Column('view_count', sa.Integer(), nullable=True, comment='查看次数'))
    op.alter_column('metric_applications', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('metric_applications', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='应用名称',
               existing_nullable=False)
    op.alter_column('metric_applications', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_metric_applications_id'), 'metric_applications', ['id'], unique=False)
    op.drop_column('metric_applications', 'metric_ids')
    op.drop_column('metric_applications', 'status')
    op.drop_column('metric_applications', 'application_config')
    op.add_column('metric_catalogs', sa.Column('code', sa.String(length=100), nullable=False, comment='指标编码'))
    op.add_column('metric_catalogs', sa.Column('type', sa.String(length=20), nullable=False, comment='指标类型: basic/derived/composite'))
    op.add_column('metric_catalogs', sa.Column('status', sa.String(length=20), nullable=True, comment='状态: published/draft/deprecated'))
    op.add_column('metric_catalogs', sa.Column('formula', sa.Text(), nullable=True, comment='计算逻辑'))
    op.add_column('metric_catalogs', sa.Column('owner', sa.String(length=100), nullable=True, comment='负责人'))
    op.add_column('metric_catalogs', sa.Column('dimensions', sa.JSON(), nullable=True, comment='关联维度'))
    op.add_column('metric_catalogs', sa.Column('query_count', sa.Integer(), nullable=True, comment='查询次数'))
    op.add_column('metric_catalogs', sa.Column('application_count', sa.Integer(), nullable=True, comment='应用数量'))
    op.add_column('metric_catalogs', sa.Column('dependency_count', sa.Integer(), nullable=True, comment='依赖指标数'))
    op.alter_column('metric_catalogs', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('metric_catalogs', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='指标名称',
               existing_nullable=False)
    op.alter_column('metric_catalogs', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='所属分类',
               existing_nullable=True)
    op.alter_column('metric_catalogs', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.alter_column('metric_catalogs', 'tags',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='标签',
               existing_nullable=True)
    op.create_index(op.f('ix_metric_catalogs_id'), 'metric_catalogs', ['id'], unique=False)
    op.create_unique_constraint(None, 'metric_catalogs', ['code'])
    op.drop_column('metric_catalogs', 'is_active')
    op.add_column('query_history', sa.Column('conversation_id', sa.String(length=36), nullable=False))
    op.add_column('query_history', sa.Column('messages', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_query_history_conversation_id'), 'query_history', ['conversation_id'], unique=False)
    op.alter_column('system_roles', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_roles', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               comment='角色名称',
               existing_nullable=False)
    op.alter_column('system_roles', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='角色描述',
               existing_nullable=True)
    op.alter_column('system_roles', 'permissions',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='权限列表',
               existing_nullable=True)
    op.alter_column('system_roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否系统角色',
               existing_nullable=True)
    op.create_index(op.f('ix_system_roles_id'), 'system_roles', ['id'], unique=False)
    op.add_column('workbooks', sa.Column('color', sa.String(length=20), nullable=True, comment='颜色标识'))
    op.add_column('workbooks', sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/stopped'))
    op.add_column('workbooks', sa.Column('owner', sa.String(length=100), nullable=True, comment='负责人'))
    op.alter_column('workbooks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('workbooks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment='工作簿名称',
               existing_nullable=False)
    op.alter_column('workbooks', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_workbooks_id'), 'workbooks', ['id'], unique=False)
    op.drop_column('workbooks', 'is_public')
    op.drop_column('workbooks', 'content')
    op.drop_column('workbooks', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbooks', sa.Column('owner_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('workbooks', sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('workbooks', sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workbooks_id'), table_name='workbooks')
    op.alter_column('workbooks', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('workbooks', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='工作簿名称',
               existing_nullable=False)
    op.alter_column('workbooks', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('workbooks', 'owner')
    op.drop_column('workbooks', 'status')
    op.drop_column('workbooks', 'color')
    op.drop_index(op.f('ix_system_roles_id'), table_name='system_roles')
    op.alter_column('system_roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否系统角色',
               existing_nullable=True)
    op.alter_column('system_roles', 'permissions',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='权限列表',
               existing_nullable=True)
    op.alter_column('system_roles', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('system_roles', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    op.alter_column('system_roles', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_query_history_conversation_id'), table_name='query_history')
    op.drop_column('query_history', 'messages')
    op.drop_column('query_history', 'conversation_id')
    op.add_column('metric_catalogs', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'metric_catalogs', type_='unique')
    op.drop_index(op.f('ix_metric_catalogs_id'), table_name='metric_catalogs')
    op.alter_column('metric_catalogs', 'tags',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='标签',
               existing_nullable=True)
    op.alter_column('metric_catalogs', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('metric_catalogs', 'category',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='所属分类',
               existing_nullable=True)
    op.alter_column('metric_catalogs', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='指标名称',
               existing_nullable=False)
    op.alter_column('metric_catalogs', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metric_catalogs', 'dependency_count')
    op.drop_column('metric_catalogs', 'application_count')
    op.drop_column('metric_catalogs', 'query_count')
    op.drop_column('metric_catalogs', 'dimensions')
    op.drop_column('metric_catalogs', 'owner')
    op.drop_column('metric_catalogs', 'formula')
    op.drop_column('metric_catalogs', 'status')
    op.drop_column('metric_catalogs', 'type')
    op.drop_column('metric_catalogs', 'code')
    op.add_column('metric_applications', sa.Column('application_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('metric_applications', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('metric_applications', sa.Column('metric_ids', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_index(op.f('ix_metric_applications_id'), table_name='metric_applications')
    op.alter_column('metric_applications', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('metric_applications', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='应用名称',
               existing_nullable=False)
    op.alter_column('metric_applications', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metric_applications', 'view_count')
    op.drop_column('metric_applications', 'owner')
    op.drop_column('metric_applications', 'metrics')
    op.drop_column('metric_applications', 'type')
    op.add_column('metric_accelerations', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('metric_accelerations', sa.Column('last_calculated_at', mysql.DATETIME(fsp=6), nullable=True))
    op.add_column('metric_accelerations', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('metric_accelerations', sa.Column('refresh_interval', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metric_accelerations', sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('metric_accelerations', sa.Column('acceleration_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('metric_accelerations', sa.Column('metric_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.drop_index(op.f('ix_metric_accelerations_id'), table_name='metric_accelerations')
    op.alter_column('metric_accelerations', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metric_accelerations', 'cache_size')
    op.drop_column('metric_accelerations', 'last_refresh')
    op.drop_column('metric_accelerations', 'accelerated_latency')
    op.drop_column('metric_accelerations', 'original_latency')
    op.drop_column('metric_accelerations', 'hit_rate')
    op.drop_column('metric_accelerations', 'enabled')
    op.drop_column('metric_accelerations', 'refresh_policy')
    op.drop_column('metric_accelerations', 'granularity')
    op.drop_column('metric_accelerations', 'dimensions')
    op.drop_column('metric_accelerations', 'metric_code')
    op.drop_column('metric_accelerations', 'metric_name')
    op.add_column('lineage_nodes', sa.Column('data_source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('lineage_nodes', sa.Column('properties', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'lineage_nodes', type_='unique')
    op.drop_index(op.f('ix_lineage_nodes_id'), table_name='lineage_nodes')
    op.alter_column('lineage_nodes', 'node_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='节点类型: source/operator/target',
               existing_nullable=False)
    op.alter_column('lineage_nodes', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='节点名称',
               existing_nullable=False)
    op.alter_column('lineage_nodes', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('lineage_nodes', 'downstream')
    op.drop_column('lineage_nodes', 'upstream')
    op.drop_column('lineage_nodes', 'row_count')
    op.drop_column('lineage_nodes', 'execution_time')
    op.drop_column('lineage_nodes', 'fields')
    op.drop_column('lineage_nodes', 'detail')
    op.drop_column('lineage_nodes', 'type')
    op.drop_column('lineage_nodes', 'node_id')
    op.add_column('lineage_connections', sa.Column('properties', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('lineage_connections', sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True))
    op.add_column('lineage_connections', sa.Column('source_node_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.add_column('lineage_connections', sa.Column('target_node_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.create_foreign_key('lineage_connections_ibfk_1', 'lineage_connections', 'lineage_nodes', ['source_node_id'], ['id'])
    op.create_foreign_key('lineage_connections_ibfk_2', 'lineage_connections', 'lineage_nodes', ['target_node_id'], ['id'])
    op.drop_index(op.f('ix_lineage_connections_id'), table_name='lineage_connections')
    op.alter_column('lineage_connections', 'connection_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               comment=None,
               existing_comment='连接类型')
    op.alter_column('lineage_connections', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('lineage_connections', 'color')
    op.drop_column('lineage_connections', 'to_node')
    op.drop_column('lineage_connections', 'from_node')
    op.add_column('integration_tasks', sa.Column('last_run_at', mysql.DATETIME(fsp=6), nullable=True))
    op.add_column('integration_tasks', sa.Column('schedule_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('integration_tasks', sa.Column('source_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('integration_tasks', sa.Column('target_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_index(op.f('ix_integration_tasks_id'), table_name='integration_tasks')
    op.alter_column('integration_tasks', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('integration_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='状态: running/paused/failed/success',
               existing_nullable=True)
    op.alter_column('integration_tasks', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='任务名称',
               existing_nullable=False)
    op.alter_column('integration_tasks', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('integration_tasks', 'last_run_duration')
    op.drop_column('integration_tasks', 'last_run_time')
    op.drop_column('integration_tasks', 'interval_minutes')
    op.drop_column('integration_tasks', 'cron_expr')
    op.drop_column('integration_tasks', 'schedule_type')
    op.drop_column('integration_tasks', 'schedule')
    op.drop_column('integration_tasks', 'target_type')
    op.drop_column('integration_tasks', 'source_type')
    op.add_column('data_accelerations', sa.Column('source_dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.add_column('data_accelerations', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('data_accelerations', sa.Column('refresh_schedule', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('data_accelerations', sa.Column('last_refresh_at', mysql.DATETIME(fsp=6), nullable=True))
    op.add_column('data_accelerations', sa.Column('acceleration_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.create_foreign_key('data_accelerations_ibfk_1', 'data_accelerations', 'datasets', ['source_dataset_id'], ['id'])
    op.drop_index(op.f('ix_data_accelerations_id'), table_name='data_accelerations')
    op.alter_column('data_accelerations', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('data_accelerations', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='任务名称',
               existing_nullable=False)
    op.alter_column('data_accelerations', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('data_accelerations', 'cache_size')
    op.drop_column('data_accelerations', 'last_refresh')
    op.drop_column('data_accelerations', 'storage')
    op.drop_column('data_accelerations', 'next_run')
    op.drop_column('data_accelerations', 'accelerated_latency')
    op.drop_column('data_accelerations', 'original_latency')
    op.drop_column('data_accelerations', 'speedup')
    op.drop_column('data_accelerations', 'enabled')
    op.drop_column('data_accelerations', 'schedule')
    op.drop_column('data_accelerations', 'refresh_policy')
    op.drop_column('data_accelerations', 'query')
    op.drop_column('data_accelerations', 'source_table')
    op.drop_column('data_accelerations', 'type')
    op.add_column('consolidation_rules', sa.Column('rule_config', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('consolidation_rules', sa.Column('apply_to', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('consolidation_rules', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_consolidation_rules_id'), table_name='consolidation_rules')
    op.alter_column('consolidation_rules', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('consolidation_rules', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='规则名称',
               existing_nullable=False)
    op.alter_column('consolidation_rules', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('consolidation_rules', 'exec_count')
    op.drop_column('consolidation_rules', 'enabled')
    op.drop_column('consolidation_rules', 'condition')
    op.drop_column('consolidation_rules', 'strategy')
    op.drop_column('consolidation_rules', 'target_table')
    op.drop_column('consolidation_rules', 'source_tables')
    op.drop_column('consolidation_rules', 'type')
    op.add_column('audit_logs', sa.Column('resource_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', mysql.DATETIME(fsp=6), nullable=True))
    op.add_column('audit_logs', sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='操作详情',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               comment=None,
               existing_comment='操作类型')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'target')
    op.drop_column('audit_logs', 'user')
    op.drop_column('audit_logs', 'time')
    op.create_table('relations',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('relation_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('source_dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('target_dataset_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('join_conditions', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.id'], name='relations_ibfk_1'),
    sa.ForeignKeyConstraint(['target_dataset_id'], ['datasets.id'], name='relations_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sql_analysis',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('original_query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('analyzed_query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('query_plan', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('performance_metrics', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('recommendations', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('data_relations')
    op.drop_index(op.f('ix_sql_analyses_id'), table_name='sql_analyses')
    op.drop_table('sql_analyses')
    # ### end Alembic commands ###