<template>
  <div class="field-config-panel">
    <div class="panel-header">
      <span class="field-name">{{ field?.name || '选择字段' }}</span>
      <span class="field-type">{{ field?.type }}</span>
    </div>
    
    <a-form v-if="field" :model="config" layout="vertical" size="small">
      <!-- 基本信息 -->
      <a-collapse :default-active-key="['basic']">
        <a-collapse-item key="basic" header="基本信息">
          <a-form-item label="字段名称">
            <a-input :value="field.name" disabled />
          </a-form-item>
          <a-form-item label="字段类型">
            <a-input :value="field.type" disabled />
          </a-form-item>
          <a-form-item label="描述">
            <a-textarea v-model="config.description" placeholder="字段描述" :auto-size="{ minRows: 2 }" />
          </a-form-item>
        </a-collapse-item>

        <!-- 值范围配置 -->
        <a-collapse-item key="range" header="值范围配置">
          <template v-if="isNumericType">
            <a-form-item label="最小值">
              <a-input-number v-model="config.value_range.min" placeholder="最小值" style="width: 100%" />
            </a-form-item>
            <a-form-item label="最大值">
              <a-input-number v-model="config.value_range.max" placeholder="最大值" style="width: 100%" />
            </a-form-item>
          </template>
          <a-empty v-else description="仅数值类型支持范围配置" />
        </a-collapse-item>

        <!-- 字典表配置 -->
        <a-collapse-item key="dict" header="字典表配置">
          <a-form-item label="关联字典">
            <a-select v-model="config.dict_id" placeholder="选择字典" allow-clear>
              <a-option v-for="dict in dictionaries" :key="dict.id" :value="dict.id">
                {{ dict.name }}
              </a-option>
            </a-select>
          </a-form-item>
          <a-button type="dashed" long @click="showCreateDict = true">
            <template #icon><icon-plus /></template>
            创建新字典
          </a-button>
        </a-collapse-item>

        <!-- 枚举值配置 -->
        <a-collapse-item key="enum" header="枚举值配置">
          <a-form-item>
            <template #label>
              <span>枚举值列表</span>
              <a-button type="text" size="mini" @click="handleAutoGenerate" :loading="generating">
                <icon-sync /> 自动生成
              </a-button>
            </template>
            <div class="enum-list">
              <a-tag 
                v-for="(val, idx) in config.enum_values" 
                :key="idx" 
                closable 
                @close="removeEnumValue(idx)"
              >
                {{ val }}
              </a-tag>
            </div>
            <a-input-group style="margin-top: 8px">
              <a-input v-model="newEnumValue" placeholder="添加枚举值" @keyup.enter="addEnumValue" />
              <a-button type="primary" @click="addEnumValue">添加</a-button>
            </a-input-group>
          </a-form-item>
        </a-collapse-item>
      </a-collapse>

      <div class="panel-footer">
        <a-button type="primary" @click="handleSave" :loading="saving">保存配置</a-button>
      </div>
    </a-form>

    <a-empty v-else description="请选择字段进行配置" />

    <!-- 创建字典弹窗 -->
    <a-modal v-model:visible="showCreateDict" title="创建字典" @ok="handleCreateDict">
      <a-form :model="newDict" layout="vertical">
        <a-form-item label="字典名称" required>
          <a-input v-model="newDict.name" placeholder="请输入字典名称" />
        </a-form-item>
        <a-form-item label="显示名称">
          <a-input v-model="newDict.display_name" placeholder="请输入显示名称" />
        </a-form-item>
        <a-form-item label="描述">
          <a-textarea v-model="newDict.description" placeholder="请输入描述" />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { Message } from '@arco-design/web-vue'
import { getDictionaries, createDictionary, autoGenerateDictionary } from '@/api/views'
import type { FieldDictionary } from '@/api/views'

interface FieldInfo {
  name: string
  type: string
  nullable?: boolean
  comment?: string
}

interface FieldConfig {
  description: string
  value_range: { min?: number; max?: number }
  dict_id: string
  enum_values: string[]
  auto_enum: boolean
}

const props = defineProps<{
  field?: FieldInfo
  datasetId?: string
  datasourceId?: string
  initialConfig?: Partial<FieldConfig>
}>()

const emit = defineEmits<{
  (e: 'save', config: FieldConfig): void
}>()

const saving = ref(false)
const generating = ref(false)
const showCreateDict = ref(false)
const dictionaries = ref<FieldDictionary[]>([])
const newEnumValue = ref('')

const config = ref<FieldConfig>({
  description: '',
  value_range: {},
  dict_id: '',
  enum_values: [],
  auto_enum: false
})

const newDict = ref({
  name: '',
  display_name: '',
  description: ''
})

const isNumericType = computed(() => {
  if (!props.field?.type) return false
  const numericTypes = ['int', 'integer', 'bigint', 'smallint', 'decimal', 'numeric', 'float', 'double', 'number']
  return numericTypes.some(t => props.field!.type.toLowerCase().includes(t))
})

watch(() => props.field, (newField) => {
  if (newField) {
    // 重置配置
    config.value = {
      description: newField.comment || '',
      value_range: {},
      dict_id: '',
      enum_values: [],
      auto_enum: false,
      ...props.initialConfig
    }
  }
}, { immediate: true })

async function loadDictionaries() {
  try {
    dictionaries.value = await getDictionaries()
  } catch (e) {
    console.error('Failed to load dictionaries:', e)
  }
}

function addEnumValue() {
  if (!newEnumValue.value.trim()) return
  if (config.value.enum_values.includes(newEnumValue.value.trim())) {
    Message.warning('该值已存在')
    return
  }
  config.value.enum_values.push(newEnumValue.value.trim())
  newEnumValue.value = ''
}

function removeEnumValue(index: number) {
  config.value.enum_values.splice(index, 1)
}

async function handleAutoGenerate() {
  if (!props.datasourceId || !props.datasetId || !props.field) {
    Message.warning('缺少必要参数')
    return
  }
  
  generating.value = true
  try {
    const dict = await autoGenerateDictionary({
      datasource_id: props.datasourceId,
      dataset_id: props.datasetId,
      column_name: props.field.name,
      dictionary_name: `${props.field.name}_dict`,
      limit: 500
    })
    
    // 更新枚举值
    config.value.enum_values = dict.mappings?.map(m => m.value) || []
    config.value.dict_id = dict.id
    
    // 刷新字典列表
    await loadDictionaries()
    
    Message.success('自动生成成功')
  } catch (e: any) {
    Message.error(e.message || '自动生成失败')
  } finally {
    generating.value = false
  }
}

async function handleCreateDict() {
  if (!newDict.value.name) {
    Message.error('请输入字典名称')
    return
  }
  
  try {
    const dict = await createDictionary({
      name: newDict.value.name,
      display_name: newDict.value.display_name,
      description: newDict.value.description,
      source_type: 'manual',
      mappings: []
    })
    
    dictionaries.value.push(dict)
    config.value.dict_id = dict.id
    showCreateDict.value = false
    
    // 重置表单
    newDict.value = { name: '', display_name: '', description: '' }
    
    Message.success('创建成功')
  } catch (e: any) {
    Message.error(e.message || '创建失败')
  }
}

function handleSave() {
  saving.value = true
  try {
    emit('save', { ...config.value })
    Message.success('保存成功')
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  loadDictionaries()
})
</script>

<style scoped>
.field-config-panel {
  padding: 12px;
}

.panel-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  background: #f7f8fa;
  border-radius: 6px;
  margin-bottom: 16px;
}

.field-name {
  font-weight: 600;
  color: #1d2129;
}

.field-type {
  font-size: 12px;
  color: #86909c;
  background: #e5e6eb;
  padding: 2px 8px;
  border-radius: 4px;
}

.enum-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  min-height: 32px;
  padding: 8px;
  background: #f7f8fa;
  border-radius: 4px;
}

.panel-footer {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid #e5e6eb;
}
</style>
